mixed-port: 7890
tproxy-port: 7893
redir-port: 7891

allow-lan: true
bind-address: "*"
external-controller: 0.0.0.0:9090
secret: 'BFC8rqg0umu-qay-xtq'

log-level: info
dns:
  enable: true
  enhanced-mode: fake-ip
