mixed-port: 7890
socks-port: 7891
tproxy-port: 7893
redir-port: 7892

allow-lan: true
bind-address: "*"
external-controller: 0.0.0.0:9090
secret: 'BFC8rqg0umu-qay-xtq'

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

log-level: info
dns:
  enable: true
  listen: 127.0.0.1:1053

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true